//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BId { get; set; }
        public string Bname { get; set; }
        public string Bauthor { get; set; }
        public Nullable<int> Bprice { get; set; }
        public Nullable<int> no_of_books { get; set; }
        public int catagry_Id { get; set; }
    
        public virtual catagry catagry { get; set; }
    }
}
