//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibrary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UsersTable
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="This field is required")]
        [StringLength(8 , MinimumLength = 4 ,ErrorMessage ="please enter from 5 to 9 chracters ")]
        public string Username { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Role")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [StringLength(11,MinimumLength =11,ErrorMessage ="please enter 11 numbers")]
        public string PhoneNo { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public int Age { get; set; }
    }
}
